#!/usr/bin/python

import dbus
import os
import sys

reload(sys)
sys.setdefaultencoding('utf8')

if sys.argv[-1] == "--togglePlayPause":
	os.system("dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause")

try:
	bus = dbus.SessionBus()
	spotify = bus.get_object("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2")
	spotify_iface = dbus.Interface(spotify, 'org.freedesktop.DBus.Properties')
	props = spotify_iface.Get('org.mpris.MediaPlayer2.Player', 'Metadata')
	print(props['xesam:artist'][0] + " - " + props['xesam:title'])
	exit
except dbus.exceptions.DBusException:
	exit
